# Generated by Django 4.2 on 2024-10-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_mediafile_media_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='target',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
